{% set name = "compas_view2" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59e00cc6255c1c18f70270749405be70dabe3a6dcb9ea65ec484395398e36475

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - compas >=1.0
    - python.app    # [osx]
    - freeglut      # [win]
    - freetype-py
    - pyside2
    - pyopengl
    - textdistance
    - qtpy
    # - pyopengl-accelerate

test:
  imports:
    - compas_view2

about:
  home: https://github.com/compas-dev/compas_view2
  license: MIT
  license_file: LICENSE
  summary: Second generation viewers for the COMPAS framework
  dev_url: https://github.com/compas-dev/compas_view2
  doc_url: https://compas.dev/compas_view2

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
